version: "3.8"

services:
  
  nginx:
    image: nginx:1.19-alpine
    restart: "no"
    ports:
      - 9000:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
    depends_on:
      - php_back
      - database

  php_back:
    image: registry.gitlab.com/qkstudio/sadaic/backoffice:testing
    restart: "always"
    networks:
      - app-network
    extra_hosts:
      - sadaic.org.ar:10.30.110.20
      - www.sadaic.org.ar:10.30.110.20

  database:
    image: mariadb:10.5.6-focal
    restart: "no"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-toor}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-backoffice}
      MYSQL_USER: ${MYSQL_USER:-backoffice}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-backoffice}

networks:
  app-network:
    driver: bridge
    name: sadaic-network

volumes:
  dbdata:
    name: sadaic-dbdata